version: '3.8'

services:
  greenhouse-edge:
    build: .
    container_name: my-greenhouse-app
    ports:
      - "80:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env # Docker Compose leerá este archivo automáticamente